# Generated by Django 4.1.3 on 2022-11-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
